"use strict";

// The GLSL that draws the same picture as js/render/cpu.js, one small pass at
// a time. The shaders repeat the CPU's arithmetic rather than approximating
// it, down to the way JavaScript's hash loses the low bits of a multiply, so
// both paths land on the same noise instead of merely the same kind.

export var GLSL_COMMON = [
  "#version 300 es",
  "precision highp float;",
  "precision highp int;",
  "uniform int uW;",
  "uniform int uH;",
  "uniform ivec4 uBox;",
  "out vec4 fragColour;",
  "",
  "ivec2 pixCoord() { return ivec2(int(gl_FragCoord.x), uH - 1 - int(gl_FragCoord.y)); }",
  "bool inBox(ivec2 p) { return p.x >= uBox.x && p.y >= uBox.y && p.x <= uBox.z && p.y <= uBox.w; }",
  "",
  "int bitLength(uint v) {",
  "  int n = 0;",
  "  if (v >= 65536u) { v >>= 16u; n += 16; }",
  "  if (v >= 256u) { v >>= 8u; n += 8; }",
  "  if (v >= 16u) { v >>= 4u; n += 4; }",
  "  if (v >= 4u) { v >>= 2u; n += 2; }",
  "  if (v >= 2u) { v >>= 1u; n += 1; }",
  "  if (v >= 1u) { n += 1; }",
  "  return n;",
  "}",
  "",
  "// JavaScript multiplies the two 32-bit numbers in its hash as doubles,",
  "// which quietly drops the low bits of a product that wide. Repeating that",
  "// here is what keeps both paths on the same noise.",
  "uint jsMul(uint k) {",
  "  bool neg = (k & 2147483648u) != 0u;",
  "  uint a = neg ? (0u - k) : k;",
  "  uint a1 = a >> 16u, a0 = a & 65535u;",
  "  uint m1 = 19441u, m0 = 40801u;",   // 1274126177, split over sixteen bits
  "  uint t0 = a0 * m0, t1 = a1 * m0, t2 = a0 * m1, t3 = a1 * m1;",
  "  uint c = (t0 >> 16u) + (t1 & 65535u) + (t2 & 65535u);",
  "  uint low = (t0 & 65535u) | ((c & 65535u) << 16u);",
  "  uint hi = t3 + (t1 >> 16u) + (t2 >> 16u) + (c >> 16u);",
  "  int n = hi != 0u ? 32 + bitLength(hi) : bitLength(low);",
  "  int drop = n - 53;",
  "  if (drop > 0) {",
  "    uint mask = (1u << uint(drop)) - 1u;",
  "    uint rem = low & mask;",
  "    uint midPoint = 1u << uint(drop - 1);",
  "    bool up = rem > midPoint || (rem == midPoint && ((low >> uint(drop)) & 1u) == 1u);",
  "    low = (low & (~mask)) + (up ? (mask + 1u) : 0u);",
  "  }",
  "  return neg ? (0u - low) : low;",
  "}",
  "",
  "float hash01(int x, int y, int seed) {",
  "  uint h = uint(x) * 374761393u + uint(y) * 668265263u + uint(seed) * 2147483647u;",
  "  h = jsMul(h ^ (h >> 13u));",
  "  return float(h ^ (h >> 16u)) / 4294967296.0;",
  "}",
  "",
  "// The cell size arrives as tenths so the grid line lands on the same pixel",
  "// as the CPU's double division does.",
  "float vnoise(ivec2 p, int c10, int seed) {",
  "  int X = p.x * 10, Y = p.y * 10;",
  "  int gx = X / c10, gy = Y / c10;",
  "  float fx = float(X - gx * c10) / float(c10);",
  "  float fy = float(Y - gy * c10) / float(c10);",
  "  float a = hash01(gx, gy, seed);",
  "  float b = hash01(gx + 1, gy, seed);",
  "  float c = hash01(gx, gy + 1, seed);",
  "  float d = hash01(gx + 1, gy + 1, seed);",
  "  float u = fx * fx * (3.0 - 2.0 * fx);",
  "  float v = fy * fy * (3.0 - 2.0 * fy);",
  "  return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v;",
  "}",
  ""
].join("\n");

export var GLSL_VERT = [
  "#version 300 es",
  "in vec2 aPos;",
  "void main() { gl_Position = vec4(aPos, 0.0, 1.0); }"
].join("\n");

// one triangle that covers the stage; every pass is the same draw
var GLSL_FIELD = [
  "uniform vec2 uCentre;",
  "uniform vec2 uSize;",
  "uniform int uSeed;",
  "uniform int uGround;",
  "uniform int uCap;",
  "uniform int uLumpCount;",
  "uniform vec3 uLumps[28];",
  "",
  "float lumpCover(vec2 q) {",
  "  float cover = 0.0;",
  "  for (int i = 0; i < uLumpCount; i++) {",
  "    vec2 e = q - uLumps[i].xy;",
  "    cover = max(cover, 1.0 - (e.x * e.x + e.y * e.y) / (uLumps[i].z * uLumps[i].z));",
  "  }",
  "  return cover;",
  "}",
  ""
].join("\n");

export var GLSL_MASK_FIRE = GLSL_COMMON + GLSL_FIELD + [
  "uniform float uWob;",
  "uniform float uTear;",
  "uniform vec2 uInvSq;",
  "uniform int uBody;",
  "uniform int uHoleCount;",
  "uniform vec4 uHoles[4];",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  if (!inBox(p)) { fragColour = vec4(float(uCap) / 255.0, 0.0, 0.0, 1.0); return; }",
  "  vec2 q = vec2(float(p.x) + 0.5, float(p.y) + 0.5);",
  "  vec2 body = (q - uCentre) / (uSize * 0.92);",
  "  float cover = uBody == 1 ? max(0.0, 1.0 - dot(body, body)) : 0.0;",
  "  cover = max(cover, lumpCover(q));",
  "  float f = cover > 0.0 ? cover - (vnoise(p, 34, uSeed) - 0.5) * 0.36 * uWob : -1.0;",
  "  if (f <= 0.2 || p.y > uGround) { fragColour = vec4(0.0, 0.0, 0.0, 1.0); return; }",
  "  float hole = 0.0;",
  "  for (int i = 0; i < uHoleCount; i++) {",
  "    vec2 e = (q - uHoles[i].xy) / uHoles[i].zw;",
  "    hole = max(hole, 1.0 - dot(e, e));",
  "  }",
  "  if (hole > 0.0 && hole >= 0.2 + (vnoise(p, 40, uSeed + 43) - 0.5) * 0.8 +",
  "      (hash01(p.x, p.y, uSeed + 47) - 0.5) * (0.3 + uTear)) {",
  "    fragColour = vec4(0.0, 0.0, 0.0, 1.0); return;",
  "  }",
  "  vec2 n = q - uCentre;",
  "  float q2 = n.x * n.x * uInvSq.x + n.y * n.y * uInvSq.y;",
  "  float grain = vnoise(p, 80, uSeed + 3) * 0.7 + vnoise(p, 32, uSeed + 7) * 0.3;",
  "  bool solid = grain > uTear * (0.35 + 1.15 * clamp(q2, 0.0, 1.2));",
  "  fragColour = vec4(solid ? float(uCap) / 255.0 : 0.0, 0.0, 0.0, 1.0);",
  "}"
].join("\n");

export var GLSL_MASK_SMOKE = GLSL_COMMON + GLSL_FIELD + [
  "uniform float uTear;",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  if (!inBox(p)) { fragColour = vec4(float(uCap) / 255.0, 0.0, 0.0, 1.0); return; }",
  "  vec2 q = vec2(float(p.x) + 0.5, float(p.y) + 0.5);",
  "  float cover = lumpCover(q);",
  "  if (cover <= 0.0 || p.y > uGround) { fragColour = vec4(0.0, 0.0, 0.0, 1.0); return; }",
  "  if (cover - (vnoise(p, 36, uSeed + 5) - 0.5) * 0.55 <= 0.18) { fragColour = vec4(0.0, 0.0, 0.0, 1.0); return; }",
  "  float grain = vnoise(p, 65, uSeed + 9) * 0.62 + vnoise(p, 28, uSeed + 15) * 0.38;",
  "  fragColour = vec4(grain > uTear ? float(uCap) / 255.0 : 0.0, 0.0, 0.0, 1.0);",
  "}"
].join("\n");

// One sweep of the chamfer distance. Ten of these reach as deep as the
// colour bands ever look; the CPU gets there in two passes because it can
// carry a running minimum along a row, which a shader cannot.
export var GLSL_DIST = GLSL_COMMON + [
  "uniform sampler2D uPrev;",
  "uniform int uCap;",
  "",
  "int depthAt(ivec2 p) {",
  "  if (!inBox(p) || p.x < 0 || p.y < 0 || p.x >= uW || p.y >= uH) return uCap;",
  "  return int(texelFetch(uPrev, ivec2(p.x, uH - 1 - p.y), 0).r * 255.0 + 0.5);",
  "}",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  if (!inBox(p)) { fragColour = vec4(float(uCap) / 255.0, 0.0, 0.0, 1.0); return; }",
  "  int d = depthAt(p);",
  "  if (d == 0) { fragColour = vec4(0.0, 0.0, 0.0, 1.0); return; }",
  "  int m = d;",
  "  m = min(m, depthAt(p + ivec2(-1, 0)) + 3);",
  "  m = min(m, depthAt(p + ivec2(1, 0)) + 3);",
  "  m = min(m, depthAt(p + ivec2(0, -1)) + 3);",
  "  m = min(m, depthAt(p + ivec2(0, 1)) + 3);",
  "  m = min(m, depthAt(p + ivec2(-1, -1)) + 4);",
  "  m = min(m, depthAt(p + ivec2(1, -1)) + 4);",
  "  m = min(m, depthAt(p + ivec2(-1, 1)) + 4);",
  "  m = min(m, depthAt(p + ivec2(1, 1)) + 4);",
  "  fragColour = vec4(float(min(m, uCap)) / 255.0, 0.0, 0.0, 1.0);",
  "}"
].join("\n");

var GLSL_PALETTE = [
  "uniform vec3 uPalette[8];",
  "vec3 fire(int band) { return uPalette[5 - clamp(band, 0, 5)]; }",
  ""
].join("\n");

export var GLSL_PAINT_FIRE = GLSL_COMMON + GLSL_PALETTE + [
  "uniform sampler2D uDepth;",
  "uniform vec2 uCentre;",
  "uniform vec2 uInvBand;",
  "uniform float uCyc;",
  "uniform float uHeat;",
  "uniform float uCore;",
  "uniform float uBite;",
  "uniform float uDither;",
  "uniform int uSeed;",
  "uniform int uLock;",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  if (!inBox(p)) discard;",
  "  int raw = int(texelFetch(uDepth, ivec2(p.x, uH - 1 - p.y), 0).r * 255.0 + 0.5);",
  "  if (raw == 0) discard;",
  "  float d = float(raw) / 3.0;",
  "  if (uBite > 0.0 && d < 2.0 && hash01(p.x, p.y, uSeed + 29) < uBite * (d < 1.2 ? 1.0 : 0.4)) discard;",
  "  float v = d + (hash01(p.x, p.y, uSeed + 37) - 0.5) * 1.15 * uDither +",
  "            (vnoise(p, 30, uSeed + 31) - 0.5) * 1.7 * uDither;",
  "  float band = v < 1.8 ? 1.0 : (v < 3.2 ? 2.0 : (v < 5.0 ? 3.0 : (v < 8.0 ? 4.0 : 5.0)));",
  "  float nx = (float(p.x) + 0.5 - uCentre.x) * uInvBand.x;",
  "  float ny = (float(p.y) + 0.5 - uCyc) * uInvBand.y;",
  "  v = band + uHeat + uCore * clamp(1.0 - (nx * nx + ny * ny), 0.0, 1.0) +",
  "      (vnoise(p, 90, uSeed + 53) - 0.5) * 0.7;",
  "  if (v < -0.45) discard;",
  "  vec3 col;",
  "  if (uLock == 1) {",
  "    col = fire(int(floor(v + 0.5)));",
  "  } else {",
  "    float f = clamp(v, 0.0, 5.0);",
  "    int lo = int(f);",
  "    col = floor(mix(fire(lo), fire(lo < 5 ? lo + 1 : 5), f - float(lo)) + 0.5);",
  "  }",
  "  fragColour = vec4(col / 255.0, 1.0);",
  "}"
].join("\n");

export var GLSL_PAINT_SMOKE = GLSL_COMMON + GLSL_PALETTE + [
  "uniform sampler2D uDepth;",
  "uniform float uTear;",
  "uniform float uStep;",
  "uniform int uSeed;",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  if (!inBox(p)) discard;",
  "  int raw = int(texelFetch(uDepth, ivec2(p.x, uH - 1 - p.y), 0).r * 255.0 + 0.5);",
  "  if (raw == 0) discard;",
  "  float d = float(raw) / 3.0;",
  "  if (d < 1.2 && hash01(p.x, p.y, uSeed + 13) < 0.3 + uTear * 0.35) discard;",
  "  if (d < 2.4 && vnoise(p, 22, uSeed + 17) > 0.82) discard;",
  "  float glow = vnoise(p, 30, uSeed + 19);",
  "  vec3 col;",
  "  if (uStep > 20.0 && uStep < 38.0 && glow > 0.76 && d < 3.0) {",
  "    col = glow > 0.84 ? uPalette[4] : uPalette[5];",
  "  } else {",
  "    col = hash01(p.x, p.y, uSeed + 23) > 0.95 ? uPalette[7] : uPalette[6];",
  "  }",
  "  fragColour = vec4(col / 255.0, 1.0);",
  "}"
].join("\n");

export var GLSL_EXTRAS = GLSL_COMMON + GLSL_PALETTE + [
  "uniform vec2 uCentre;",
  "uniform int uSeed;",
  "uniform int uGround;",
  "uniform int uRayCount;",
  "uniform vec4 uRays[16];",
  "uniform int uSpeckCount;",
  "uniform vec3 uSpecks[26];",
  "uniform int uDustCount;",
  "uniform vec4 uDust[10];",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  bool hit = false;",
  "  vec3 col = vec3(0.0);",
  "",
  "  for (int k = 0; k < uRayCount; k++) {",
  "    vec4 r = uRays[k];",
  "    float t = (float(p.x) + 0.5 - uCentre.x) * r.x + (float(p.y) + 0.5 - uCentre.y) * r.y;",
  "    if (t < r.z - 3.0 || t > r.w + 3.0) continue;",
  "    int j0 = int(floor((t - r.z) / 0.6 + 0.5));",
  "    for (int j = max(0, j0 - 3); j <= j0 + 3; j++) {",
  "      float n = r.z + 0.6 * float(j);",
  "      if (n >= r.w) break;",
  "      int x = int(floor(uCentre.x + r.x * n + 0.5));",
  "      int y = int(floor(uCentre.y + r.y * n + 0.5));",
  "      if (y > uGround) continue;",
  "      if (x == p.x && y == p.y) { hit = true; col = uPalette[0]; }",
  "      if (n < r.z + (r.w - r.z) * 0.62) {",
  "        if (x - int(floor(r.y + 0.5)) == p.x && y + int(floor(r.x + 0.5)) == p.y) { hit = true; col = uPalette[0]; }",
  "      }",
  "    }",
  "  }",
  "",
  "  for (int k = 0; k < uSpeckCount; k++) {",
  "    vec3 s = uSpecks[k];",
  "    int sx = int(s.x), sy = int(s.y), flags = int(s.z);",
  "    vec3 tone = (flags & 2) != 0 ? uPalette[5] : uPalette[4];",
  "    if (p.x == sx && p.y == sy) { hit = true; col = tone; }",
  "    if ((flags & 1) != 0) {",
  "      if (p.x == sx + 1 && p.y == sy) { hit = true; col = tone; }",
  "      if (p.x == sx && p.y == sy + 1) { hit = true; col = (flags & 2) != 0 ? uPalette[4] : uPalette[3]; }",
  "    }",
  "    if ((flags & 4) != 0 && p.x == sx && p.y == sy - 1) { hit = true; col = uPalette[4]; }",
  "  }",
  "",
  "  for (int k = 0; k < uDustCount; k++) {",
  "    vec4 g = uDust[k];",
  "    if (p.y != int(g.y)) continue;",
  "    int len = int(g.z);",
  "    for (int i = 0; i < len; i++) {",
  "      int x = int(g.x) + i;",
  "      if (x == p.x && hash01(x, p.y, int(g.w)) > 0.35) { hit = true; col = uPalette[6]; }",
  "    }",
  "  }",
  "",
  "  if (!hit) discard;",
  "  fragColour = vec4(col / 255.0, 1.0);",
  "}"
].join("\n");

export var GLSL_COMPOSITE = GLSL_COMMON + [
  "uniform sampler2D uFrame;",
  "uniform sampler2D uBack;",
  "uniform ivec2 uShake;",
  "",
  "void main() {",
  "  ivec2 p = pixCoord();",
  "  ivec2 s = p - uShake;",
  "  vec4 f = vec4(0.0);",
  "  if (s.x >= 0 && s.y >= 0 && s.x < uW && s.y < uH) f = texelFetch(uFrame, ivec2(s.x, uH - 1 - s.y), 0);",
  "  vec4 back = texelFetch(uBack, ivec2(p.x, uH - 1 - p.y), 0);",
  "  fragColour = vec4(f.a > 0.5 ? f.rgb : back.rgb, 1.0);",
  "}"
].join("\n");
